Repository kubic-project/salt, pull requests merged in 2018-12, with the labels that each got.

#699 [3.0] Fix bsc#1116933: Add a dummy state to prevent empty state in orch
  salt/migrations/cri/pre-update.sls
Labels: release-3.0-backport

#641 [3.0] [CPI] Add self-signed certificate to CPI configuration, bsc#1101973
  salt/kubernetes-common/openstack-config.jinja
Labels: awaiting-merge, release-3.0-backport

#642 [3.0] [CPI] Fix and remove empty lines in OpenStack cpi config, bsc#1101973
  salt/kubernetes-common/openstack-config.jinja
Labels: awaiting-merge, release-3.0-backport

#643 [3.0] [CPI] Add option to ignore OpenStack Cinder availability zone, bsc#1095572
  pillar/params.sls
  salt/kubernetes-common/openstack-config.jinja
Labels: awaiting-merge, release-3.0-backport

#689 [3.0] Fix bsc#1116005: Dex pods should run only on master nodes
  salt/addons/dex/manifests/20-deployment.yaml
Labels: bug, release-3.0-backport

#691 [3.0] Generate the /etc/hosts file with a custom state
  salt/_modules/caasp_hosts.py
  salt/_modules/tests/__init__.py
  salt/_modules/tests/test_caasp_hosts.py
  salt/_states/caasp_hosts.py
  salt/etc-hosts/hosts.jinja
  salt/etc-hosts/init.sls
  salt/etc-hosts/update-pre-reboot.sls
Labels: release-3.0-backport
