Repository kubic-project/salt, pull requests merged in 2018-08, with the labels that each got.

#634 [3.0] Salt 2018 compatibility
  config/master.d/50-reactor.conf
  config/master.d/50-returner.conf
  reactor/sync-modules.sls
  reactor/update-mine.sls
  salt/_beacons/default_network_interface_settings.py
  salt/_modules/caasp_filters.py
  salt/_modules/caasp_http.py
  salt/_modules/caasp_log.py
  salt/_modules/caasp_nodes.py
  salt/addons/dex/init.sls
  salt/orch/update.sls
Labels: release-3.0-backport

#607 Salt 2018 compatibility
  config/master.d/50-reactor.conf
  reactor/sync-modules.sls
  reactor/update-mine.sls
  salt/_beacons/default_network_interface_settings.py
  salt/_modules/caasp_filters.py
  salt/_modules/caasp_http.py
  salt/_modules/caasp_log.py
  salt/_modules/caasp_nodes.py
  salt/addons/dex/init.sls
  salt/orch/update.sls
Labels: release-3.0-candidate

#635 HAProxy will refuse to start if it cannot resolve any name.
  salt/haproxy/init.sls
Labels: release-3.0-candidate

#646 Reintroduce kubelet drain timeout and abort if draining fails
  pillar/params.sls
  salt/kubelet/stop.sls
Labels: release-3.0-candidate

#652 Fix bsc#1101004 removes unsused pillars for transactional updates
  pillar/params.sls
Labels: bug

#648 Create RoleBinding to allow dex discovery
  salt/addons/dex/manifests/10-rolebinding.yaml
Labels: release-3.0-candidate

#636 [3.0] HAProxy will refuse to start if it cannot resolve any name.
  salt/haproxy/init.sls
Labels: release-3.0-backport

#649 [3.0] Create RoleBinding to allow dex discovery
  salt/addons/dex/manifests/10-rolebinding.yaml
Labels: release-3.0-backport

#647 [3.0] Reintroduce kubelet drain timeout and abort if draining fails
  pillar/params.sls
  salt/kubelet/stop.sls
Labels: release-3.0-backport
