Repository kubic-project/salt, pull requests merged in 2018-11, with the labels that each got.

#680 [3.0][bsc#1114645] Move deprecated flags to kubelet config.yaml
  salt/kubelet/init.sls
  salt/kubelet/kubelet-config.jinja
  salt/kubelet/kubelet.jinja
Labels: bug, release-3.0-backport

#678 Add a whitelist for returned events so we only save events that we care about
  config/master.d/50-master.conf
Labels: release-3.0-candidate

#675 [3.0] configure aggregation layer, bsc#108195
  pillar/certificates.sls
  salt/kube-apiserver/apiserver.jinja
  salt/kube-apiserver/init.sls
Labels: awaiting-merge, release-3.0-backport

#679 [3.0] Add a whitelist for returned events so we only save events that we care about
  config/master.d/50-master.conf
Labels: awaiting-merge, release-3.0-backport

#687 [3.0][k8s 1.10] don't run haproxy states when not really needed
  salt/orch/update.sls
Labels: release-3.0-backport

#694 [3.0] Workaround bsc#1116933: remove /var/lib/container on crio installation
  salt/_modules/caasp_cri.py
  salt/migrations/cri/clean-up-crio-pods.sh
  salt/migrations/cri/pre-update.sls
  salt/orch/update.sls
Labels: release-3.0-backport
