Repository kubic-project/salt, pull requests merged in 2018-06, with the labels that each got.

#583 [3.0] fix get node targets
  salt/_modules/caasp_etcd.py
  salt/_modules/caasp_grains.py
  salt/_modules/caasp_net.py
  salt/_modules/caasp_nodes.py
  salt/_modules/tests/test_caasp_nodes.py
  salt/_states/caasp_cri.py
  salt/_states/caasp_http.py
  salt/_states/caasp_retriable.py
  salt/_states/caasp_service.py
  salt/etc-hosts/hosts.jinja
  salt/etcd/etcd.conf.jinja
  salt/haproxy/haproxy.cfg.jinja
  salt/orch/removal.sls
Labels: release-3.0-backport

#585 [3.0] Uncordon node in a explicit sls action
  salt/kubelet/init.sls
  salt/kubelet/update-post-start-services.sls
  salt/orch/update.sls
Labels: bug, release-3.0-backport

#584 Uncordon node in a explicit sls action
  salt/kubelet/init.sls
  salt/kubelet/update-post-start-services.sls
  salt/orch/update.sls
Labels: bug, release-3.0-candidate

#586 Use the cache whenever something bad happens when refreshing the Pillar.
  salt/_pillar/velum.py
Labels: release-3.0-candidate

#587 [3.0] Use the cache whenever something bad happens when refreshing the Pillar.
  salt/_pillar/velum.py
Labels: release-3.0-backport

#589 Also stop `kubelet` on masters when performing an upgrade
  salt/orch/update.sls
Labels: bug, release-3.0-candidate

#590 [3.0] Also stop `kubelet` on masters when performing an upgrade
  salt/orch/update.sls
Labels: bug, release-3.0-backport

#591 Force `etc-hosts` sls to be run before `etcd`
  salt/orch/update.sls
Labels: bug, release-3.0-candidate

#592 [3.0] Force `etc-hosts` sls to be run before `etcd`
  salt/orch/update.sls
Labels: bug, release-3.0-backport

#594 [3.0] Remove mine information when removing a node
  salt/orch/force-removal.sls
  salt/orch/removal.sls
Labels: release-3.0-backport

#593 Remove mine information when removing a node
  salt/orch/force-removal.sls
  salt/orch/removal.sls
Labels: release-3.0-candidate

#596 [3.0] Fix some orchestration flags
  salt/orch/kubernetes.sls
Labels: release-3.0-backport

#598 [3.0] Early setup some services on updates
  salt/addons/psp/manifests/10-podsecuritypolicy-privileged.yaml
  salt/addons/psp/manifests/10-podsecuritypolicy-unprivileged.yaml
  salt/orch/update.sls
Labels: release-3.0-backport

#600 [3.0] Try to load the manifests once we have at least one updated master.
  salt/orch/update.sls
Labels: P1 Bug, bug, release-3.0-backport

#603 [3.0] Move the early services setup before updating the masters
  salt/addons/init.sls
  salt/addons/psp/init.sls
  salt/cni/init.sls
  salt/cni/update-post-reboot.sls
  salt/orch/update.sls
Labels: P1 Bug, bug, release-3.0-backport

#602 Move the early services setup before updating masters.
  salt/addons/init.sls
  salt/addons/psp/init.sls
  salt/cni/init.sls
  salt/cni/update-post-reboot.sls
  salt/orch/update.sls
Labels: P1 Bug, bug, release-3.0-candidate

#578 override volume plugin dir (bsc#1084766)
  salt/kubelet/kubelet.jinja
Labels: P2 bug, release-3.0-candidate

#608 During upgrade, ensure masters always have the correct taints
  salt/kubelet/update-pre-orchestration.sh
  salt/kubelet/update-pre-orchestration.sls
Labels: release-3.0-candidate

#609 During upgrade, ensure masters always have the correct taints
  salt/kubelet/update-pre-orchestration.sh
  salt/kubelet/update-pre-orchestration.sls
Labels: release-3.0-backport

#612 [3.0] Call to `mine.update` after `saltutil.sync_pillar` has been called.
  salt/orch/update.sls
Labels: bug, release-3.0-backport

#611 Call to `mine.update` after `saltutil.sync_pillar` has been called.
  salt/orch/update.sls
Labels: bug, release-3.0-candidate
