Repository kubic-project/salt, pull requests merged in 2018-10, with the labels that each got.

#664 Always wait for haproxy to be serving requests before continuing
  salt/haproxy/init.sls
  salt/migrations/2-3/haproxy/init.sls
Labels: release-3.0-candidate

#665 [3.0] Always wait for haproxy to be serving requests before continuing
  salt/haproxy/init.sls
  salt/migrations/2-3/haproxy/init.sls
Labels: release-3.0-backport

#670 [3.0] Fix bsc#1111168: Do not expect masters to always need to be updated
  salt/orch/update.sls
Labels: bug, release-3.0-backport

#673 [3.0] Fix bsc#1111168: Do not expect masters to always need to be updated
  salt/orch/update.sls
Labels: bug, release-3.0-backport

#633 [3.0] Configure addon pod affinity
  salt/addons/dns/manifests/20-deployment.yaml
  salt/addons/tiller/manifests/20-deployment.yaml
Labels: release-3.0-backport

#656 [3.0] CAdvisor is publicly exposed on the kubernetes nodes(:::4194) (bsc#1105910)
  salt/kubelet/kubelet.jinja
Labels: release-3.0-backport

#660 [3.0] Allow `etcd` to grow as required and shrink to optimal etcd cluster sizes on corner cases
  salt/_modules/caasp_etcd.py
  salt/_modules/caasp_nodes.py
  salt/_modules/tests/test_caasp_etcd.py
  salt/_states/caasp_etcd.py
  salt/cleanup/etcd.sls
  salt/etcd/etcd.conf.jinja
  salt/etcd/etcdctl.conf.jinja
  salt/etcd/init.sls
  salt/etcd/remove-pre-orchestration.sls
  salt/etcd/remove.sls
  salt/kube-apiserver/remove-pre-orchestration.sls
  salt/kubelet/remove-post-orchestration.sls
  salt/orch/force-removal.sls
  salt/orch/kubernetes.sls
  salt/orch/removal.sls
Labels: no-bugzilla-ref, release-3.0-backport

#659 [3.0] Adds annotation to use docker/default seccomp profile (bsc#1099045)
  salt/addons/dex/manifests/20-deployment.yaml
  salt/addons/dns/manifests/20-deployment.yaml
  salt/haproxy/haproxy.yaml.jinja
  salt/migrations/2-3/haproxy/haproxy.yaml.jinja
Labels: release-3.0-backport

#676 [3.0] fix for bsc#1111333
  salt/crypto/init.sls
Labels: release-3.0-backport

#614 Allow `etcd` to grow as required and shrink to optimal etcd cluster sizes on corner cases
  salt/_modules/caasp_etcd.py
  salt/_modules/caasp_nodes.py
  salt/_modules/tests/test_caasp_etcd.py
  salt/_states/caasp_etcd.py
  salt/cleanup/etcd.sls
  salt/etcd/etcd.conf.jinja
  salt/etcd/init.sls
  salt/etcd/remove.sls
  salt/kubelet/remove-post-orchestration.sls
  salt/orch/force-removal.sls
  salt/orch/kubernetes.sls
  salt/orch/removal.sls
Labels: release-3.0-candidate
