Repository kubic-project/salt, pull requests merged in 2018-05, with the labels that each got.

#516 [bsc#1092140] enable psp opt-out
  salt/addons/dns/init.sls
  salt/addons/psp/init.sls
  salt/addons/tiller/deployment-wait.sls
  salt/addons/tiller/init.sls
  salt/cleanup/remove-post-orchestration.sls
  salt/cni/cilium/init.sls
  salt/etc-hosts/init.sls
  salt/etcd/update-pre-orchestration.sls
  salt/etcd/update-pre-reboot.sls
  salt/kube-apiserver/apiserver.jinja
  salt/transactional-update/init.sls
Labels: bug, release-3.0-candidate

#521 [3.0] [bsc#1092140] enable psp opt-out
  salt/addons/dns/init.sls
  salt/addons/psp/init.sls
  salt/addons/tiller/deployment-wait.sls
  salt/addons/tiller/init.sls
  salt/cleanup/remove-post-orchestration.sls
  salt/cni/cilium/init.sls
  salt/etc-hosts/init.sls
  salt/etcd/update-pre-orchestration.sls
  salt/etcd/update-pre-reboot.sls
  salt/kube-apiserver/apiserver.jinja
  salt/transactional-update/init.sls
Labels: bug, release-3.0-backport

#538 Only remove the master grains if there are any masters to be updated.
  salt/orch/update.sls
Labels: release-3.0-candidate

#539 [3.0] Only remove the master grains if there are any masters to be updated.
  salt/orch/update.sls
Labels: release-3.0-backport

#542 Lower the per-request timeout when we are checking for successful query
  salt/_modules/caasp_http.py
  salt/_states/caasp_http.py
  salt/addons/dex/wait.sls
  salt/haproxy/init.sls
  salt/kube-apiserver/init.sls
Labels: release-3.0-candidate

#543 [3.0] Lower the per-request timeout when we are checking for successful query
  salt/_modules/caasp_http.py
  salt/_states/caasp_http.py
  salt/addons/dex/wait.sls
  salt/haproxy/init.sls
  salt/kube-apiserver/init.sls
Labels: release-3.0-backport

#546 [3.0] Remove default grace period and timeout when draining a node.
  salt/kubelet/stop.sls
Labels: release-3.0-backport

#545 Remove default grace period and timeout when draining a node.
  salt/kubelet/stop.sls
Labels: release-3.0-candidate

#536 skip removed etcd servers (bsc#1093305)
  salt/kube-apiserver/apiserver.jinja
Labels: bug, release-3.0-candidate

#550 Provide configuration to transactional-update
  salt/transactional-update/init.sls
  salt/transactional-update/transactional-update.conf
Labels: release-3.0-backport

#553 Add support for kube API auditing
  pillar/kube-master.sls
  salt/kube-apiserver/apiserver.jinja
  salt/kube-apiserver/init.sls
Labels: release-3.0-backport

#554 Remove unneeded state
  salt/addons/dex/init.sls
  salt/docker/init.sls
  salt/etcd/init.sls
  salt/kube-apiserver/init.sls
  salt/kube-controller-manager/init.sls
  salt/kube-proxy/init.sls
  salt/kube-scheduler/init.sls
  salt/kubelet/init.sls
  salt/kubernetes-common/init.sls
  salt/repositories/containers.repo
  salt/repositories/init.sls
  salt/top.sls
Labels: release-3.0-backport

#537 also reload docker when certificates change
  salt/docker/init.sls
Labels: release-3.0-candidate

#557 [3.0] skip removed etcd servers (bsc#1093305)
  salt/kube-apiserver/apiserver.jinja
Labels: bug, release-3.0-backport

#560 Log all CRI issues as we go, and show them if we really timeout
  salt/_modules/caasp_cri.py
Labels: release-3.0-candidate

#561 [3.0] Log all CRI issues as we go, and show them if we really timeout
  salt/_modules/caasp_cri.py
Labels: release-3.0-backport

#569 [3.0] fix docker reload again
  salt/crio/init.sls
  salt/docker/init.sls
Labels: release-3.0-backport

#571 [3.0] Fix bsc#1091809: pillar and openstack config can use project and doma…
  pillar/params.sls
  salt/kubernetes-common/openstack-config.jinja
Labels: release-3.0-backport

#562 Fix kubelet arguments
  salt/kubelet/kubelet.jinja
Labels: release-3.0-candidate

#563 [3.0] Fix kubelet arguments
  salt/kubelet/kubelet.jinja
Labels: release-3.0-backport
