Repository kubic-project/salt, pull requests merged in 2019-02, with the labels that each got.

#709 [bsc#1116049] don't fail timing out on a drain
  salt/kubelet/stop.sls
Labels: P2 bug

#692 [3.0] Add log rotation options to docker daemon (bug#1114832)
  pillar/docker.sls
  salt/docker/daemon.json.jinja
Labels: bug, release-3.0-backport, release-3.0-backport-merged

#682 [3.0] Enable `ExperimentalCriticalPodAnnotation` feature gate in the kubelet
  salt/kubelet/kubelet-config.jinja
Labels: release-3.0-backport

#716 [3.0] [CPI] Sanitize the values from the pillar (bsc#1122439)
  salt/kubernetes-common/openstack-config.jinja
Labels: release-3.0-backport

#720 caasp_filters: properly parse IP addresses
  salt/_modules/caasp_filters.py
  salt/_modules/tests/test_caasp_filters.py
Labels: release-3.0-backport

#719 [3.0][bsc#1116049] don't fail timing out on a drain
  salt/kubelet/stop.sls
Labels: P2 bug, release-3.0-backport

#725 Jenkinsfile: Use docker cmdline directly instead of k8s Jenkins plugin
  Jenkinsfile.flake8
  Jenkinsfile.tests
Labels: release-3.0-backport

#726 [3.0] Run salt tests with the proper version for the 3.0 release
  Jenkinsfile.tests
Labels: release-3.0-backport

#728 Sort nodenames first when generating /etc/hosts entries
  salt/_modules/caasp_hosts.py
  salt/_modules/tests/test_caasp_hosts.py
Labels: P1 Bug

#727 [bsc#1125095] deployment timeout not correctly configured
  salt/_macros/kubectl.jinja
Labels: bug

#708 [k8s 1.13][bsc#1122783] update critical pod configuration
  salt/addons/dex/manifests/20-deployment.yaml
  salt/addons/dns/manifests/20-deployment.yaml
  salt/addons/tiller/manifests/20-deployment.yaml
  salt/cni/cilium-ds.yaml.jinja
  salt/cni/kube-flannel.yaml.jinja
  salt/haproxy/haproxy.yaml.jinja
Labels: bug
