Repository kubic-project/salt, pull requests merged in 2019-01, with the labels that each got.

#706 Run tox based tests using a pre-baked tox container
  Jenkinsfile.flake8
  Jenkinsfile.tests
Labels: no-bugzilla-ref, release-3.0-backport

#701 update etcdctl sysconfig with ENDPOINTS flag (bsc#1120047)
  salt/etcd/etcdctl.conf.jinja
Labels: release-3.0-backport

#684 3.0-backport: Add support for OIDC connectors to dex configmap (bsc#1116376)
  salt/addons/dex/manifests/15-configmap.yaml
Labels: release-3.0-backport

#681 Enable `ExperimentalCriticalPodAnnotation` feature gate in the kubelet
  salt/kubelet/kubelet-config.jinja
Labels: release-3.0-candidate
